name: Autocloser
on: [issues, pull_request]
jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
    - name: Autoclose issues that did not follow issue template
      uses: roots/issue-closer@v1.1
      with:
        repo-token: ${{ secrets.TOKEN }}
        issue-close-message: "this issue was automatically closed."
        issue-pattern: ".*guidelines for Contributing.*"
